:prod-auth = Autorization: Basic <BASE64 encoded user:pass>
:bc-url = https://es-client.op4mi.gm.com
:prod-url = https://es-client.op4wi.gm.com

# GET INDICES

GET :prod-url/_cat/indices
:prod-auth

# GET ALIASES

GET :prod-url/_cat/aliases
:prod-auth

# POST ADD/REMOVE ALIASES

POST :bc-url/_aliases
:prod-auth
Content-Type: application/json

{
  "actions": [{
      "remove": {
        "index": "aspn_gm_gvs-voq__v2.6",
        "alias": "sf_gm_gvs"
      }
    },
    {
      "remove": {
        "index": "aspn_gm_gvs-voq__v2.6",
        "alias": "sf_gm_gvs__1"
      }
    }
  ]
}


# DELETE INDEX

:index = BE_CAREFUL
DELETE :bc-url/:index
:prod-auth

# GET DOC COUNT 
:index = aspn_gm_gvs-gart__2016_04__v3.0
GET :bc-url/:index/_count
:prod-auth

# Search for raptr stuff
:index = aspn_gm_gvs-gart*__v3.0
GET :bc-url/:index/_search
:prod-auth
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "exists": {
            "field": "signafire.raptr_nonmatching_models"
          }
        }
      ]
    }
  }
}


# PUT SKI-CUTTER MAPPING

PUT :bc-url/ski-cutter
:prod-auth
Content-Type: application/json

{
  "mappings" : {
    "properties" : {
      "uuid" : {
        "type" : "text"
      },
      "status" : {
        "type" : "nested",
        "properties" : {
          "start-time" : {
            "type" : "date"
          },
          "finish-time" : {
            "type" : "date"
          },
          "application-name" : {
            "type" : "text"
          },
          "state" : {
            "type" : "text"
          },
          "final-state" : {
            "type" : "text"
          }
        }
      },
      "query-params": {
        "type" : "nested"
      }
    }
  }
}

# GET A DOC

GET :bc-url/aspn_gm_*gart__2016_02__v3.0/_search
:prod-auth
Content-Type: application/json

{ "size": 100,
  "query": {"term":{"jobCardDate": "2016-02-01"}}

}

# {
#   "size": 1,
#   "query": {
#       "term": {
#        "odino": "11221667"
#       }
#   }
# }

# Allow wildcard delete
PUT :bc-url/_cluster/settings
:prod-auth
Content-Type: application/json

{
    "transient": {
    	"action.destructive_requires_name": false
    }
}


##############################
# ASPN ELASTICSEARCH STAGING #
##############################

:staging-url = https://es-kibana:es-kibana@es-client.op-epg5mi.gm.com

# GET INDICES

GET :staging-url/_cat/indices

# GET ALIASES

GET :staging-url/_cat/aliases

# GET DOC COUNT

:index = aspn_gm_gvs-gart__2016_04__v3.0
GET :staging-url/:index/_count

# POST ADD / REMOVE ALIASES

POST :staging-url/_aliases
Content-Type: application/json

{
  "actions": [{
      "add": {
        "index": "aspn_gm_ussiebel-ussiebel__2018_02__v3.8.0421",
        "alias": "sf_gm_gvs"
      }
    },
    {
      "add": {
        "index": "aspn_gm_ussiebel-ussiebel__2018_03__v3.8.0421",
        "alias": "sf_gm_gvs"
      }
    },
    {
      "add": {
        "index": "aspn_gm_ussiebel-ussiebel__2018_01__v3.8.0421",
        "alias": "sf_gm_gvs"
      }
    },
    {
      "add": {
        "index": "aspn_gm_ussiebel-ussiebel__2018_02__v3.8.0421",
        "alias": "sf_gm_gvs__2018_02"
      }
    },
    {
      "add": {
        "index": "aspn_gm_ussiebel-ussiebel__2018_03__v3.8.0421",
        "alias": "sf_gm_gvs__2018_03"
      }
    },
    {
      "add": {
        "index": "aspn_gm_ussiebel-ussiebel__2018_01__v3.8.0421",
        "alias": "sf_gm_gvs__2018_01"
      }
    }
  ]
}

# GET activity count - needs work
GET :bc-url/aspn_gm*-voq_*0501/_search
:prod-auth
Content-Type: application/json

{
  "size": 0,
  "aggs": {
    "count_activity": {
      "nested": {
        "path": "activity"
      },
      "aggs": {
        "top_reverse_nested": {
          "reverse_nested": {}
        }
      }
    },
    "max_edw_dt": {
      "max": {
        "field": "edwETLDatetime"
      }
    }
  }
}

# aspn bug 2020-09-25

GET :prod-url/aspn_gm_gvscore-gvscore__v2.6/_search
:prod-auth
Content-Type: application/json

{
  "size": 1,
  "query": {
      "term": {
       "incidentId": "213252"
      }
  }
}

# mapping

GET :prod-url/aspn_gm_gvscore-gvscore__v2.6/_mapping
:prod-auth
C